# Generated by Django 4.2.7 on 2023-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=50)),
                ('detalleEmprendimiento', models.CharField(max_length=1000)),
                ('imagenEmprendimiento', models.CharField(max_length=250)),
                ('estadoEmprendimiento', models.CharField(max_length=50)),
            ],
        ),
    ]
