# Generated by Django 4.2.7 on 2023-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='estadoEmprendimiento',
            field=models.CharField(choices=[('valido', 'Valido'), ('no_valido', 'No Valido')], max_length=50),
        ),
    ]
