# Generated by Django 4.2.7 on 2023-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0002_alter_emprendimiento_estadoemprendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='estadoEmprendimiento',
            field=models.CharField(choices=[('Valido', 'Valido'), ('No Valido', 'No Valido')], max_length=50),
        ),
    ]
