# Generated by Django 4.2.7 on 2023-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0003_alter_emprendimiento_estadoemprendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='imagenEmprendimiento',
            field=models.ImageField(upload_to='emprendimiento/'),
        ),
    ]
