# Generated by Django 4.2.7 on 2023-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0004_alter_emprendimiento_imagenemprendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='imagenEmprendimiento',
            field=models.ImageField(null=True, upload_to='emprendimiento/'),
        ),
    ]
